# basic options
title: Deseq2 report generator
author: Adam Cribbs
email: adam.cribbs@ndorms.ox.ac.uk
description: This is a repo containing the code that allows you to automatically generate a DESeq2 report
twitter_username: CribbsP
github_username:  Acribbs

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# urls
# your gh-pages url: https://username.github.io
url: https://acribbs.github.io
# your repository name: /repository
baseurl: /deseq2_report
